services:
  sso-db:
    image: postgres:13
    container_name: sso-db
    expose:
      - 5431
    ports:
      - 5431:5431
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5431
    volumes:
      - ./local/database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
      - ./.bin/db-setup.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - sso-requests-data:/var/lib/postgresql/data
    networks:
      - css-net

  dev-keycloak:
    container_name: dev-keycloak
    image: ghcr.io/bcgov/sso:7.6.39-build.2
    depends_on:
      - sso-db
    ports:
      - 9080:9080
    environment:
      DB_POSTGRESQL_SERVICE_HOST: sso-db
      DB_POSTGRESQL_SERVICE_PORT: 5431
      DB_USERNAME: keycloak
      DB_PASSWORD: keycloak
      DB_DATABASE: keycloak
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      TZ: America/Vancouver
      JAVA_OPTS_APPEND: '-Djboss.socket.binding.port-offset=1000 -Djboss.persistent.log.dir=/opt/eap'
      KC_HEALTH_ENABLED: 'true'
    networks:
      css-net:
        aliases: ['dev-keycloak.localtest.me']

  test-keycloak:
    container_name: test-keycloak
    image: ghcr.io/bcgov/sso:7.6.39-build.2
    depends_on:
      - sso-db
    ports:
      - 9081:9081
    environment:
      DB_POSTGRESQL_SERVICE_HOST: sso-db
      DB_POSTGRESQL_SERVICE_PORT: 5431
      DB_USERNAME: keycloak
      DB_PASSWORD: keycloak
      DB_DATABASE: keycloak-test
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      TZ: America/Vancouver
      JAVA_OPTS_APPEND: '-Djboss.socket.binding.port-offset=1001 -Djboss.persistent.log.dir=/opt/eap'
      KC_HEALTH_ENABLED: 'true'
    networks:
      css-net:
        aliases: ['test-keycloak.localtest.me']

  prod-keycloak:
    container_name: prod-keycloak
    image: ghcr.io/bcgov/sso:7.6.39-build.2
    depends_on:
      - sso-db
    ports:
      - 9082:9082
    environment:
      DB_POSTGRESQL_SERVICE_HOST: sso-db
      DB_POSTGRESQL_SERVICE_PORT: 5431
      DB_USERNAME: keycloak
      DB_PASSWORD: keycloak
      DB_DATABASE: keycloak-prod
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      TZ: America/Vancouver
      JAVA_OPTS_APPEND: '-Djboss.socket.binding.port-offset=1002 -Djboss.persistent.log.dir=/opt/eap'
      KC_HEALTH_ENABLED: 'true'
    networks:
      css-net:
        aliases: ['prod-keycloak.localtest.me']

  dev-kc-migration:
    container_name: dev-kc-migration
    depends_on:
      - dev-keycloak
    image: tf-modules-migrator:latest
    environment:
      HEALTH_CHECK_URL: http://dev-keycloak.localtest.me:9080
      TF_VAR_keycloak_url: http://dev-keycloak:9080
      TF_VAR_username: admin
      TF_VAR_password: admin
      KC_ENV: dev
    build:
      context: .
      dockerfile: ./Dockerfile.tf-modules
    volumes:
      - sso-kc-terraform-dev:/terraform
    networks:
      - css-net

  test-kc-migration:
    container_name: test-kc-migration
    depends_on:
      - test-keycloak
    image: tf-modules-migrator:latest
    environment:
      HEALTH_CHECK_URL: http://test-keycloak.localtest.me:9081
      TF_VAR_keycloak_url: http://test-keycloak:9081
      TF_VAR_username: admin
      TF_VAR_password: admin
      KC_ENV: test
    build:
      context: .
      dockerfile: ./Dockerfile.tf-modules
    volumes:
      - sso-kc-terraform-test:/terraform
    networks:
      - css-net

  prod-kc-migration:
    container_name: prod-kc-migration
    depends_on:
      - prod-keycloak
    image: tf-modules-migrator:latest
    environment:
      HEALTH_CHECK_URL: http://prod-keycloak.localtest.me:9082
      TF_VAR_keycloak_url: http://prod-keycloak:9082
      TF_VAR_username: admin
      TF_VAR_password: admin
      KC_ENV: prod
    build:
      context: .
      dockerfile: ./Dockerfile.tf-modules
    volumes:
      - sso-kc-terraform-prod:/terraform
    networks:
      - css-net

  realm-registry-migration:
    container_name: realm-registry-migration
    depends_on:
      - sso-db
    image: tf-modules-migrator:latest
    environment:
      HEALTH_CHECK_URL: http://prod-keycloak.localtest.me:9082
      TF_VAR_keycloak_url: http://prod-keycloak:9082
      TF_VAR_username: admin
      TF_VAR_password: admin
      KC_ENV: prod
    build:
      context: .
      dockerfile: ./Dockerfile.tf-modules
    volumes:
      - sso-kc-terraform-prod:/terraform
    networks:
      - css-net
volumes:
  sso-requests-data:
    driver: local
  sso-kc-terraform-dev:
    driver: local
  sso-kc-terraform-test:
    driver: local
  sso-kc-terraform-prod:
    driver: local
networks:
  css-net: {}
