apiVersion: v1
name: realm-registry
version: 0.1.0
appVersion: 0.1.0
description: Nextjs application to manage SSO keycloak custom realm profiles
dependencies:
  - name: patroni
    version: 1.1.2
    repository: https://bcgov.github.io/sso-helm-charts
  - name: backup-storage
    version: 0.1.10
    repository: https://bcgov.github.io/helm-charts
    alias: backupDB
