apiVersion: v1
name: realm-registry
version: 0.2.2
appVersion: 0.1.0
description: Nextjs application to manage SSO keycloak custom realm profiles
dependencies:
  - name: patroni
    version: 1.5.1
    repository: https://bcgov.github.io/sso-helm-charts
