replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso-realm-registry
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: realm-registry-app
fullnameOverride: realm-registry-app

service:
  type: ClusterIP
  port: 8080

route:
  host:

sso:
  url: http://localhost:8080
  redirectUri: http://localhost:3000
  logoutRedirectUri: http://localhost:3000
  authorizationResponseType: code
  authorizationScope: openid
  tokenGrantType: authorization_code

postgres:
  host: realm-registry-patroni
  port: 5432
  username:
    secret: realm-registry-patroni-appusers
    key: username-appuser1
  password:
    secret: realm-registry-patroni-appusers
    key: password-appuser1
  database: realm_registry
  ssl: true

jwt:
  tokenExpiry: 1h

env: {}
extraEnv: {}
envSecret: realm-registry

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

backupDB:
  nameOverride: backup-storage
  fullnameOverride: backup-storage

  backupConfig: |
    postgres=realm-registry-patroni:5432/realm_registry
    0 1 * * * default ./backup.sh -s
    0 4 * * * default ./backup.sh -s all

  db:
    secretName: realm-registry-patroni-appusers
    usernameKey: username-appuser1
    passwordKey: password-appuser1

  persistence:
    backup:
      size: 1Gi
