image:
  tag: main

route:
  host: realm-registry.apps.gold.devops.gov.bc.ca

sso:
  url: https://loginproxy.gov.bc.ca/auth/realms/standard
  redirectUri: http://realm-registry.apps.gold.devops.gov.bc.ca/oidc/keycloak
  logoutRedirectUri: http://realm-registry.apps.gold.devops.gov.bc.ca

env:
  APP_ENV: 'production'
  SECURE_HEADERS: 'true'
  IDIR_JWKS_URI: https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs
  IDIR_ISSUER: https://loginproxy.gov.bc.ca/auth/realms/standard
  IDIR_AUDIENCE: css-app-in-gold-4128
  CHES_API_ENDPOINT: https://ches.api.gov.bc.ca/api/v1/email

vault:
  vaultSecretEngine: c6af30-prod
  postgresSecret: prod-realm-registry-patroni-appusers
  realmRegistrySecret: prod-realm-registry
  serviceAccountName: c6af30-vault

patroni:
  image:
    repository: registry.opensource.zalan.do/acid/spilo-14
    pullPolicy: Always
    tag: 2.1-p5

  walG:
    enabled: true
    scheduleCronJob: 00 01 * * *
    retainBackups: 7
    pvc:
      size: 1Gi
