replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso-realm-registry
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: realm-registry-app
fullnameOverride: realm-registry-app

service:
  type: ClusterIP
  port: 8080

route:
  host:

sso:
  url: http://localhost:8080
  clientId: realm-profile-app-760
  clientSecret:
    secret: realm-profile-sso-service-account
    key: client-secret
  redirectUri: http://localhost:3000
  logoutRedirectUri: http://localhost:3000
  authorizationResponseType: code
  authorizationScope: openid
  tokenGrantType: authorization_code

kc:
  dev:
    url: https://dev.oidc.gov.bc.ca
    clientId: 'script-cli'
    clientSecret:
      secret: keycloak-cli-service-account
      key: client-secret-dev
  test:
    url: https://test.oidc.gov.bc.ca
    clientId: 'script-cli'
    clientSecret:
      secret: keycloak-cli-service-account
      key: client-secret-test
  prod:
    url: https://oidc.gov.bc.ca
    clientId: 'script-cli'
    clientSecret:
      secret: keycloak-cli-service-account
      key: client-secret-prod

postgres:
  host: realm-registry-patroni
  port: 5432
  user: postgres
  password:
    secret: realm-registry-patroni
    key: password-superuser
  database: realm_registry
  ssl: true

jwt:
  secret:
  tokenExpiry: 1h

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
