image:
  tag: dev

route:
  host: realm-registry-dev.apps.silver.devops.gov.bc.ca

sso:
  url: https://dev.oidc.gov.bc.ca/auth/realms/onestopauth
  redirectUri: http://realm-registry-dev.apps.silver.devops.gov.bc.ca/oidc/keycloak
  logoutRedirectUri: http://realm-registry-dev.apps.silver.devops.gov.bc.ca

env:
  SECURE_HEADERS: 'true'
  IDIR_JWKS_URI: https://dev.oidc.gov.bc.ca/auth/realms/onestopauth/protocol/openid-connect/certs
  IDIR_ISSUER: https://dev.oidc.gov.bc.ca/auth/realms/onestopauth

patroni:
  image:
    repository: ghcr.io/junminahn/spilo
    pullPolicy: Always
    tag: 2.1-p5

  walG:
    enabled: true
    scheduleCronJob: 00 01 * * *
    retainBackups: 2
    pvc:
      size: 1Gi
