image:
  tag: main

sso:
  url: https://oidc.gov.bc.ca/auth/realms/onestopauth
  redirectUri: http://realm-registry.apps.silver.devops.gov.bc.ca/oidc/keycloak
  logoutRedirectUri: http://realm-registry.apps.silver.devops.gov.bc.ca

env:
  SECURE_HEADERS: 'true'
  IDIR_JWKS_URI: https://oidc.gov.bc.ca/auth/realms/onestopauth/protocol/openid-connect/certs
  IDIR_ISSUER: https://oidc.gov.bc.ca/auth/realms/onestopauth

vault:
  vaultSecretEngine:  b861c7-prod
  secretName: prod-realm-registry-patroni-appusers
  realmRegistrySecret: prod-realm-registry

patroni:
  image:
    repository: ghcr.io/junminahn/spilo
    pullPolicy: Always
    tag: 2.1-p5

  walG:
    enabled: true
    scheduleCronJob: 00 01 * * *
    retainBackups: 7
    pvc:
      size: 2Gi
