name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Test JQ
        env:
          JSON: ${{ toJSON(secrets) }}
        run: |
          test=aa=$(echo "${{ env.JSON }}" | sed -E 's/([^\]|^)"/\1\\"/g')
          echo "$test"
          echo $(jq -r 'keys[] as $k | "--set env.\($k)=\(.[$k])"' <<< "$test")
