name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: View context attributes
        id: set-result
        uses: actions/github-script@v6
        with:
          script: |
            const aa = JSON.stringify(${{ toJSON(secrets) }}).replace(/\"/g, '\\"');
            const data = JSON.parse(JSON.stringify(${{ toJSON(secrets) }}));
            console.log(Object.keys(data));
            return aa;
          result-encoding: string
      - name: Test JQ
        run: |
          echo $(jq -r 'keys[] as $k | "--set env.\($k)=\(.[$k])"' <<< "${{steps.set-result.outputs.result}}")
