name: Create and publish Realm Registry App image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'app/**'
      - 'helm/**'
      - '.github/workflows/publish-image.yml'

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: bcgov/sso-realm-registry

jobs:
  build-and-push-image:
    permissions: write-all
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: 'patch'
          tag_prefix: 'v'
          use_github_release_notes: 'true'
          release_name: 'Release <RELEASE_VERSION>'
          max_commits: 100 # default is 50

      - id: get-tag
        name: Get Tag
        run: |
          echo "release_tag=${{ endsWith(github.ref, '/main') && steps.release.outputs.tag_name || steps.meta.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: app
          push: true
          tags: ${{ endsWith(github.ref, '/main') && format('{0}/{1}:{2}', env.GITHUB_REGISTRY, env.IMAGE_NAME, steps.release.outputs.tag_name) || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Set env to development
        if: (github.ref == 'refs/heads/dev' && github.event_name == 'push')
        run: |
          cat >> $GITHUB_ENV <<EOF
          OPENSHIFT_TOKEN=${{ secrets.DEV_OPENSHIFT_TOKEN }}
          OPENSHIFT_NAMESPACE=${{ secrets.DEV_OPENSHIFT_NAMESPACE }}
          EOF

      - name: Set env to production
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
        run: |
          cat >> $GITHUB_ENV <<EOF
          OPENSHIFT_TOKEN=${{ secrets.PROD_OPENSHIFT_TOKEN }}
          OPENSHIFT_NAMESPACE=${{ secrets.PROD_OPENSHIFT_NAMESPACE }}
          EOF

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          insecure_skip_tls_verify: true

      - name: Deploy app with Helm chart
        run: |
          namespace=${{ env.OPENSHIFT_NAMESPACE }}
          helm dep up
          helm upgrade --install --atomic realm-registry . -n ${namespace} \
          -f values.yaml -f "values-${namespace}.yaml" --set image.tag="${{ steps.get-tag.outputs.release_tag }}"
        working-directory: ./helm/webapp
