name: Run unit tests

on: push

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
      - run: |
          cd app
          yarn
          yarn test
